version: '3.3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: 'expenses'
      # So you don't have to use root, but you can if you like
      MARIADB_USER: 'expenses_app'
      # You can use whatever password you like
      MARIADB_PASSWORD: 'jirameki22'
      # Password for root access
      MARIADB_ROOT_PASSWORD: 'jirameki22'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
